namespace auto_coursera
{
    internal class CourseData
    {
        public static Dictionary<string, Dictionary<string, string>> ITE302c = new Dictionary<
            string,
            Dictionary<string, string>
        >
        {
            {
                "MOC1",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/iyd6e/data-driven-emerging-technologies-quiz"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/2rF4o/privacy-and-legal-concepts-related-to-data-driven-technologies-quiz"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/vousp/bias-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/vA5Tl/ethical-theories-quiz"
                    },
                    {
                        "WEEK5",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/RyrAe/ethical-principles-applied-to-data-driven-technologies-quiz"
                    }
                }
            },
            {
                "MOC2",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/dFvtO/frameworks-and-ethical-responsibilities-with-data-driven-technologies-quiz"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/XINkU/application-of-ethical-frameworks-to-ethical-dilemmas-quiz"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/PVNuF/regulations-and-standards-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/t5enb/conflict-reconciliation-between-ethics-regulations-and-business-demands-quiz"
                    },
                    //{ "WEEK5", "https://example.com/page2" }
                }
            },
            {
                "MOC3",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/HqYhk/analyzing-ethical-risks"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/4MYUV/managing-privacy-risks"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/N6cA0/managing-accountability-risks-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/4CPkd/managing-transparency-and-explainability-risks-quiz"
                    },
                    {
                        "WEEK5",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/i1WSA/managing-fairness-and-non-discrimination-risks"
                    },
                    {
                        "WEEK6",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/ZSL8t/managing-safety-and-security-risks-quiz"
                    }
                }
            },
            {
                "MOC4",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/SNs9L/communicating-the-business-impacts-of-ethical-risks"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/K6TaO/designing-communication-strategies"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/5v1OD/managing-a-crisis-communicating-critical-messages-and-ensuring-business"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/wqLkP/managing-the-media-during-an-ethical-crisis"
                    },
                }
            },
            {
                "MOC5",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/Vzp5x/ethical-organizational-culture-quiz"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/zRafZ/ethical-considerations-in-governance-and-policy-making-quiz"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/Q0saz/code-of-ethics-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/j5tLn/policy-development-and-monitoring-quiz"
                    },
                }
            },
            {
                "MOC6",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/preparing-for-your-certnexus-certification-exam/exam/DLw5W/summative-assessment"
                    },
                }
            },
        };

        public static Dictionary<string, Dictionary<string, string>> WDU202c = new Dictionary<
            string,
            Dictionary<string, string>
        >
        {
            {
                "MOOC1",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/iyd6e/data-driven-emerging-technologies-quiz"
                    },
                    { "WEEK2", "https://example.com/page2" },
                    { "WEEK3", "https://example.com/page2" },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/vA5Tl/ethical-theories-quiz"
                    },
                    {
                        "WEEK5",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/RyrAe/ethical-principles-applied-to-data-driven-technologies-quiz"
                    }
                }
            },
            {
                "MOOC2",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/dFvtO/frameworks-and-ethical-responsibilities-with-data-driven-technologies-quiz"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/XINkU/application-of-ethical-frameworks-to-ethical-dilemmas-quiz"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/PVNuF/regulations-and-standards-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/t5enb/conflict-reconciliation-between-ethics-regulations-and-business-demands-quiz"
                    },
                }
            },
            {
                "MOOC3",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/HqYhk/analyzing-ethical-risks"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/4MYUV/managing-privacy-risks"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/N6cA0/managing-accountability-risks-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/4CPkd/managing-transparency-and-explainability-risks-quiz"
                    },
                    {
                        "WEEK5",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/i1WSA/managing-fairness-and-non-discrimination-risks"
                    },
                    {
                        "WEEK6",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/ZSL8t/managing-safety-and-security-risks-quiz"
                    }
                }
            },
            {
                "MOOC4",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/SNs9L/communicating-the-business-impacts-of-ethical-risks"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/K6TaO/designing-communication-strategies"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/5v1OD/managing-a-crisis-communicating-critical-messages-and-ensuring-business"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/wqLkP/managing-the-media-during-an-ethical-crisis"
                    },
                }
            },
            {
                "MOOC5",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/Vzp5x/ethical-organizational-culture-quiz"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/zRafZ/ethical-considerations-in-governance-and-policy-making-quiz"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/Q0saz/code-of-ethics-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/j5tLn/policy-development-and-monitoring-quiz"
                    },
                }
            },
            {
                "MOC6",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/preparing-for-your-certnexus-certification-exam/exam/DLw5W/summative-assessment"
                    },
                }
            },
        };

        public static Dictionary<string, Dictionary<string, Dictionary<string, string>>> All =
            new Dictionary<string, Dictionary<string, Dictionary<string, string>>>
            {
                { "ITE302c", ITE302c },
                { "WDU202c", WDU202c },
            };
    }
}
