namespace auto_coursera
{
    internal class CourseData
    {
        public static Dictionary<string, Dictionary<string, string>> ITE302c = new Dictionary<
            string,
            Dictionary<string, string>
        >
        {
            {
                "MOOC1",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/iyd6e/data-driven-emerging-technologies-quiz"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/2rF4o/privacy-and-legal-concepts-related-to-data-driven-technologies-quiz"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/vousp/bias-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/vA5Tl/ethical-theories-quiz"
                    },
                    {
                        "WEEK5",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/RyrAe/ethical-principles-applied-to-data-driven-technologies-quiz"
                    }
                }
            },
            {
                "MOOC2",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/dFvtO/frameworks-and-ethical-responsibilities-with-data-driven-technologies-quiz"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/XINkU/application-of-ethical-frameworks-to-ethical-dilemmas-quiz"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/PVNuF/regulations-and-standards-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/ethical-frameworks-action/exam/t5enb/conflict-reconciliation-between-ethics-regulations-and-business-demands-quiz"
                    },
                }
            },
            {
                "MOOC3",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/HqYhk/analyzing-ethical-risks"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/4MYUV/managing-privacy-risks"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/N6cA0/managing-accountability-risks-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/4CPkd/managing-transparency-and-explainability-risks-quiz"
                    },
                    {
                        "WEEK5",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/i1WSA/managing-fairness-and-non-discrimination-risks"
                    },
                    {
                        "WEEK6",
                        "https://www.coursera.org/learn/detect-mitigate-ethical-risks/exam/ZSL8t/managing-safety-and-security-risks-quiz"
                    }
                }
            },
            {
                "MOOC4",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/SNs9L/communicating-the-business-impacts-of-ethical-risks"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/K6TaO/designing-communication-strategies"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/5v1OD/managing-a-crisis-communicating-critical-messages-and-ensuring-business"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/ethical-communication-data-driven-technologies/exam/wqLkP/managing-the-media-during-an-ethical-crisis"
                    },
                }
            },
            {
                "MOOC5",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/Vzp5x/ethical-organizational-culture-quiz"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/zRafZ/ethical-considerations-in-governance-and-policy-making-quiz"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/Q0saz/code-of-ethics-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/ethical-data-driven-technology-leader/exam/j5tLn/policy-development-and-monitoring-quiz"
                    },
                }
            },
            {
                "MOOC6",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/preparing-for-your-certnexus-certification-exam/exam/DLw5W/summative-assessment"
                    },
                }
            },
        };

        public static Dictionary<string, Dictionary<string, string>> WDU203c = new Dictionary<
            string,
            Dictionary<string, string>
        >
        {
            {
                "MOOC1",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/iyd6e/data-driven-emerging-technologies-quiz"
                    },
                    { "WEEK2", "https://example.com/page2" },
                    { "WEEK3", "https://example.com/page2" },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/vA5Tl/ethical-theories-quiz"
                    },
                    {
                        "WEEK5",
                        "https://www.coursera.org/learn/promote-ethical-data-driven-technologies/exam/RyrAe/ethical-principles-applied-to-data-driven-technologies-quiz"
                    }
                }
            },
            {
                "MOOC2",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/understanding-user-needs/exam/qkpjF/user-needs-assessment-and-qualitative-research"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/understanding-user-needs/exam/GOPzh/peer-review-1-self-check"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/understanding-user-needs/exam/ePIY5/peer-review-2-self-check"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/understanding-user-needs/exam/XaDxi/interviewing-tips"
                    },
                    {
                        "WEEK5",
                        "https://www.coursera.org/learn/understanding-user-needs/exam/Q21pX/peer-review-3-self-check"
                    },
                    {
                        "WEEK6",
                        "https://www.coursera.org/learn/understanding-user-needs/exam/3wDAD/affinity-walls"
                    },
                    {
                        "WEEK7",
                        "https://www.coursera.org/learn/understanding-user-needs/exam/HeGOn/peer-review-4-self-check"
                    },
                    {
                        "WEEK8",
                        "https://www.coursera.org/learn/understanding-user-needs/exam/FrzAj/whole-course"
                    },
                }
            },
            {
                "MOOC3",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/evaluating-designs-with-users/exam/YgPOh/lesson-1-quiz"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/evaluating-designs-with-users/exam/cXCyS/lesson-2-quiz"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/evaluating-designs-with-users/exam/BY1oO/lesson-3-quiz"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/evaluating-designs-with-users/exam/Mtdhm/self-assessment"
                    },
                    {
                        "WEEK5",
                        "https://www.coursera.org/learn/evaluating-designs-with-users/exam/biPEa/lesson-4-quiz"
                    }
                }
            },
            {
                "MOOC4",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/ux-design-concept-wireframe/exam/OSMXC/introduction-to-the-design-process"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/ux-design-concept-wireframe/exam/9N9iK/ideation"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/ux-design-concept-wireframe/exam/YMTGo/design-constraints-and-making-choices"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/ux-design-concept-wireframe/exam/gPy8G/quiz-building-blocks-of-user-interaction"
                    },
                    {
                        "WEEK5",
                        "https://www.coursera.org/learn/ux-design-concept-wireframe/exam/AgYGO/quiz-low-to-hi-fidelity-prototyping"
                    },
                    {
                        "WEEK6",
                        "https://www.coursera.org/learn/ux-design-concept-wireframe/exam/BcTcW/quiz-conceptual-issues-in-prototyping-and-design"
                    },
                }
            },
            {
                "MOOC5",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/ux-research-at-scale/exam/YDiJh/quiz-survey-time"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/ux-research-at-scale/exam/7FUJb/quiz-assessing-your-survey-knowledge"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/ux-research-at-scale/exam/uU4pt/quiz-getting-responses"
                    },
                    {
                        "WEEK4",
                        "https://www.coursera.org/learn/ux-research-at-scale/exam/kYJEd/writing-questions-quiz-1"
                    },
                    {
                        "WEEK5",
                        "https://www.coursera.org/learn/ux-research-at-scale/exam/laZal/writing-questions-quiz-2"
                    },
                    {
                        "WEEK6",
                        "https://www.coursera.org/learn/ux-research-at-scale/exam/UJDL7/quiz-about-research-at-scale"
                    },
                    {
                        "WEEK7",
                        "https://www.coursera.org/learn/ux-research-at-scale/exam/ucHj9/remote-testing"
                    },
                }
            },
            {
                "MOOC6",
                new Dictionary<string, string>
                {
                    {
                        "WEEK1",
                        "https://www.coursera.org/learn/user-experience-capstone/exam/MoINS/quiz-needs-finding"
                    },
                    {
                        "WEEK2",
                        "https://www.coursera.org/learn/user-experience-capstone/exam/ui17o/quiz-user-testing"
                    },
                    {
                        "WEEK3",
                        "https://www.coursera.org/learn/user-experience-capstone/exam/cpD7W/quiz-iterative-prototyping"
                    },
                }
            },
        };

        public static Dictionary<string, Dictionary<string, Dictionary<string, string>>> All =
            new Dictionary<string, Dictionary<string, Dictionary<string, string>>>
            {
                { "ITE302c", ITE302c },
                { "WDU203c", WDU203c },
            };
    }
}
